os: osx
osx_image: xcode10.1
language: swift
sudo: required
install:
    - wget https://swift.org/builds/swift-4.2.1-release/xcode/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-osx.pkg
    - sudo installer -pkg swift-4.2.1-RELEASE-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/swift-4.2.1-RELEASE.xtoolchain/usr/bin:$PATH"
script:
    - swift --version
    - swift package update
    - swift test

